### ISSUE TITLE
vps源码安装出错，大佬能否更新一下docker镜像文件

### ISSUE THREAD

**Issue by rogers601** [hjdhnx/dr_py#69]
一、docker镜像虽然能运行，但是升级就会提示，代码错误，原因是镜像文件的升级代码仓库是以前弃用的，不能升级到最新版，然后docker不知道怎么使用更新代码`cd utils && wget https://ghproxy.liuzhicong.com/https://raw.githubusercontent.com/hjdhnx/dr_py/main/utils/update.py -O update.py
`，有知道的大佬如果知道方法，忘告知，感激不尽。或者有大佬分享一个最新的docker镜像文件，谢谢。

`二、使用源码安装的时候，运行app.py提示Traceback (most recent call last):
  File "/var/local/drpyy/dr_py/app.py", line 7, in <module>
    from flask.app import Flask
  File "/usr/local/lib/python3.9/dist-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.9/dist-packages/werkzeug/urls.py)
`
不知道怎么解决

**Comment by rogers601** [comment]
探究了一番，多次尝试使用源码安装最终成功，但遇到了新问题，我的服务器只有ipv6，运行后只有tcp端口开放5705，tcp6没有开放，请问如何解决

**Comment by hjdhnx** [comment]
参考主页链接 大佬地盘
进去有其他大佬编译的三方镜像支持最新版
